schema_version = "1.0.0"

id = "embroidery_importer"
name = "Embroidery Importer"
version = "0.9.4"
tagline = "Import embroidery files into Blender"
type = "add-on"
blender_version_min = "4.2.0"
maintainer = "Jasper van Loenen <mail@jaspervanloenen.com>"
website = "https://github.com/javl/blender-embroidery"
tags = ["Import-Export"]
license = [
  "SPDX:GPL-3.0-or-later",
]
repository = "https://github.com/javl/blender-embroidery"

# https://docs.blender.org/manual/en/dev/advanced/extensions/python_wheels.html
wheels = [
   "./wheels/pyembroidery-1.5.1-py2.py3-none-any.whl"
]

[permissions]
files = "Read embroidery files from disk"
